### ISSUE TITLE
Program gets stuck if Laf is installed after frame is created and JList is used.

### ISSUE THREAD

**Issue by Ilolka1337** [weisJ/darklaf#204]
**Describe the bug**
the program stops loading and loads the CPU heavily

**To Reproduce**
````java
import java.awt.*;

import javax.swing.*;
import javax.swing.border.EmptyBorder;

import com.github.weisj.darklaf.LafManager;

class Test {

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JPanel contentPane = new JPanel(new BorderLayout());
            contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));

            DefaultListModel<String> listModel = new DefaultListModel<>();
            listModel.addElement("DARKLAFLISTTEST");
            JList<String> list = new JList<>(listModel);
            contentPane.add(list);

            JFrame frame = new JFrame();
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setContentPane(contentPane);
            frame.pack();
            frame.setLocationRelativeTo(null);
            LafManager.install();

            frame.setVisible(true);
        });
    }
}
````

**Screenshots**
https://mega.nz/file/K25EjQqJ#rws_JR8zF4_ia6NXiuw3VrUptGPh9N-VmQBinsxC1VI

**Additional Information:**
- Darklaf Version: 2.4.2

**Comment by weisJ** [comment]
A few things first.
1. No content being displayed is **not** a crash.
2. Please refrain from posting videos if possible. Problems like this are fully capable of being explained through word alone.
3. Please include the code to reproduce the issue **directly** into your post. (I have done that for you this time).
4. Always try to reproduce the issue with the latest full release. Though integration version have the latest features they also have the latest bugs. It's important for me to know whether any actual releases suffer from the same problem.

Now to your problem:
Don't install the LaF after the frame has been created. That should solve it.

**Comment by Ilolka1337** [comment]
@weisJ 
I already tried installing LaF before the frame was created it didn't solve the problem even before recording that video
