### ISSUE TITLE
Unselectable element in a JTree

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#225]
**Describe the bug**

See this bug report:
https://bz.apache.org/bugzilla/show_bug.cgi?id=64984

**To Reproduce**

On Windows 10, open jmeter nightly build 5.4.1, add a Backend Listener , try to select it with the mouse

https://bz.apache.org/bugzilla/attachment.cgi?id=37613
https://bz.apache.org/bugzilla/attachment.cgi?id=37607

**Screenshots**

In bug report

**Additional Information:**
 - OS: Windows
 - OS Version: 10
- Darklaf Version:  2.5.3 

**Additional context**

**Comment by weisJ** [comment]
Thank you for the report!
The problem seems to be that the cell-hint popup is shown even though the tree cell isn't obscured. Are you able to reproduce this reliably? If yes you could try whether the current snapshot version resolves the issue.

**Comment by weisJ** [comment]
For a quick fix people can add `darklaf. treeRowPopup=false` as a property.

**Comment by pmouawad** [comment]
Hello @weisJ , 
I am not able to reproduce the issue on any of the laptop I have.
Only reporter could confirm it's fixed.

Can you clarify the following ?
- If we use latest.integration ,issue is supposed to be fixed or do we need to also add darklaf.treeRowPopup=false
- If we don't use it, will adding darklaf.treeRowPopup=false fix the issue ?

By setting property, you mean 
- System.setProperty("darklaf.treeRowPopup", "true")  
- or -Ddarklaf.treeRowPopup=true 

or something else ? 

Thanks

**Comment by pmouawad** [comment]
I've got my answer regarding property, it can be set even on non latest version

**Comment by weisJ** [comment]
> * If we use latest.integration ,issue is supposed to be fixed or do we need to also add darklaf.treeRowPopup=false

Maybe. As I am not able to replicate the issue all I can do is speculate over the source. So there is the chance that the `latest.integration` version solves the problem, but it isn't certain.

> * If we don't use it, will adding darklaf.treeRowPopup=false fix the issue ?

Yes, this property disables the popup which shows the obscured part of a tree cell, which causes the issue.
 
> By setting property, you mean
> 
> * System.setProperty("darklaf.treeRowPopup", "true")
> * or -Ddarklaf.treeRowPopup=true
> 
> or something else ?

`System.setProperty("darklaf.treeRowPopup", "false")` will work. `-Ddarklaf.treeRowPopup=false` should too which could even be used with the current version of JMeter.

**Comment by ubikloadpack** [comment]
Hello @weisJ ,
User  confirmed issue is fixed with darklaf.treeRowPopup=false

There are more details in :

- https://bz.apache.org/bugzilla/show_bug.cgi?id=64984

Regards

**Comment by FSchumacher** [comment]
The OP states that the issue appears on a HiDPI display with resolution of 3240x2160 and a text size of 225%, only. OP can't reproduce it with 200% text size or a lower resolution of 1920x1080. (Can be looked up in the bug report Philippe has linked above.

**Comment by weisJ** [comment]
I'm still trying to replicate the issue, but the fact that it only happens with certain screen resolutions/scaling combinations seems plausible. I have added some logging to the class responsible for the popups. They will be logged if `LafManager.setLogLevel(Level.FINE)` is set. If the current `latest.intergration` version doesn't resolve the issue then the logging information would be very helpful.

**Comment by weisJ** [comment]
I think I was able to track down this problem. When determining whether a cell popup is needed (to display the obscured part of the cell) the preferred size of the renderer component is calculated and compared to the actually visible bounds of the cell. Because during this calculation the renderer may have a `null` parent it can report an incorrect preferred size (due to a mismatch in the `GraphicsConfiguration` leading to incorrect `FontMetrics`). Based on the the scaling factor of the screen (which is the crucial difference between the calculation with and without the parent) the renderer component will always report a bigger preferred size than it actually takes up on screen, forcing the popup to always be displayed.

b077e3f741c3c48e23bdaf7565a2e7fd1e9107ec should mitigate this problem.
