### ISSUE TITLE
Heavyweight balloon tooltip flickers when shown

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#82]
See [#51 (comment)](https://github.com/weisJ/darklaf/issues/51#issuecomment-589187134).

**Comment by weisJ** [comment]
@vlsi Could you try if the issue persists with the latest addition?

**Comment by vlsi** [comment]
It still flickers.
Probably the very first `opacity` is calculated wrong, however, I have not verified it.

**Comment by weisJ** [comment]
494bd7dcdc2dd02f6ec274cf2f2625bcc2bb20ac hopefully fixes this.

**Comment by vlsi** [comment]
Sometimes the sizing is odd:

<img width="135" alt="tooltip is cut" src="https://user-images.githubusercontent.com/213894/77044816-25b63180-69d1-11ea-9d9c-d92236a278a2.png">

Flickering is still there.

**Comment by weisJ** [comment]
The sizing issue should be present anymore. Tooltips are now positions at the outside of the component ignoring its border.

**Comment by vlsi** [comment]
Well, the flickering is still there, and it looks like it is caused by some weird paint which happens even before `DarkTooltipUI#paint`.

I have tried setting `window.setOpacity(0f)` in `PopupFactory` (+ I replaced setComposite with setOpacity in `DarkTooltipUI#paint`), and it helped!

What do you think of using `window.setOpacity` for tooltip handling?  It probably affects popup menus as well, however, the flickering there is way way less visible.

**Comment by weisJ** [comment]
This works great! The opacity should only be set to `0` in the `PopupFactory` if the content is actually a tooltip though.

**Comment by weisJ** [comment]
I guess then this is fixed with 768c989cd229e786679d0f9524e14c7a32b91a7b

**Comment by vlsi** [comment]
>The opacity should only be set to 0 in the PopupFactory if the content is actually a tooltip though.

Why do you think so?

It looks like the same flickering happens with popup menus (e.g. with nested submenus), however, it is less pronounced there.

It looks like Swing reuses windows, so even though the background is set to transparent color, the window has the previous content, so it is shown.

**Comment by weisJ** [comment]
I see I thought that you meant that setting the opacity would cause PopupMenus to flicker. But this way they obviously should also have their opacity set.

On Windows it’s impossible to reproduce the issue as there is no way to force heavyweight popups than to make the owner of it `null` which prevents caching of already used windows.

**Comment by vlsi** [comment]
> owner of it null

It looks like Swing uses `owner` a lot, so I was not very eager to use that.

> I see I thought that you meant that setting the opacity would cause PopupMenus to flicker

Just in case: recently I suggested `window.setBackground(UIManager.getColor("PopupMenu.translucentBackground"));` which did reduce flickering a bit for menus. However it did not resolve menu flickering completely.

I guess the solution is:
1) Set opacity=0 when creating the popup
2) Set opacity to 1 for menus and/or animate opacity for tooltips

WDYT?

**Comment by weisJ** [comment]
> > owner of it null
> 
> It looks like Swing uses `owner` a lot, so I was not very eager to use that.
> 

The `owner` is only `null` if the content is a tooltip with the balloon border and no heavyweight popup was provided. The `owner` is only used as a means to cache the window, so there shouldn’t be any issue.
Currently there is no way to force heavyweight popups on Windows for tooltips that’s why this is necessary. In Java 9 there was an additional flag `heavyWeightPopup` introduced to `PopupFactory#getPopup` which simply could be overwritten and passed to the `super` implementation. In Java 8 this is not possible :/.


> 1) Set opacity=0 when creating the popup
> 
> 2) Set opacity to 1 for menus and/or animate opacity for tooltips

Shouldn’t it be the other way round i.e.

1. tooltips and menus have opacity `0` at first
2. all other tooltips have opacity `1`

**Comment by vlsi** [comment]
>2. Set opacity to 1 for menus and/or animate opacity for tooltips

Oh. I was about to say "set the opacity to 1 at the first paint"

**Comment by weisJ** [comment]
Implemented in 44e7399ad6e835dd2c0f9e6cb59cae1feb7f8a83. I removed the part where that background of the popup is set as this shouldn't be needed anymore. Can you confirm it works for you?

**Comment by vlsi** [comment]
Menu and tooltip flickering is indeed gone in 0f60e0c112a04289d41aa1f8352db2aa3119a58a
